---
title: "fMRI Project - Heat Map"
author: "Xurui Zhi"
date: "2024-03-19"
output: html_document
---

# load library
```{r}
library(ggplot2)
library(reshape2)
```


# set base directory and list all .RData files:
```{r}
# base directory that contains all .RData
base_dir <- "~/The Pennsylvania State University - Fales, Kaitlyn Rose - Scanner Heterogeneity Project/Correlation_Matrices"

# full paths to the files
file_list <- list.files(path = base_dir, pattern = "\\.RData$", full.names = TRUE, ignore.case = TRUE)
```


New code to create the overall heatmap
```{r}
############ New code ##########################

# Extract list of names to use as column names for eventual heatmap 
combinations <- gsub("\\..*","", basename(file_list))

# Make list of edges in order for how the results will be vectorized
edges <- c("MPFC & LP-L","MPFC & LP-R","LP-L & LP-R","MPFC & PCC","LP-L & PCC","LP-R & PCC")

# Matrix of heatmap results
mean_edge_weights <- matrix(NA, ncol = 6, nrow = length(file_list))
rownames(mean_edge_weights) <- combinations
colnames(mean_edge_weights) <- edges

# Function for getting mean Fisher z-transformed values for a preprocessing combination
# This function will return a vector of length 6 that will be one column in the heatmap
fisher_transform <- function(cor_matrices){
  # Empty matrix to store result
  result <- matrix(NA, nrow = 6, ncol = length(cor_matrices))

  # Take each FC matrix and vectorize the upper triangle
  for (j in 1:length(cor_matrices)){
    r.vector <- cor_matrices[[j]]*upper.tri(cor_matrices[[j]], diag = F)
    result[,j] <- r.vector[r.vector != 0]
  }

  # Fisher's z-transform
  result <- atanh(result)

  # Collapse result to get single column - take mean of each row (6-dim vector)
  out <- rowMeans(result)
  
  # Return output
  return(out)
}

# For loop to run across all 48 combinations
for (i in 1:length(file_list)){
  # Load in individual file
  load(file_list[i])
  
  # Pull the name of the file into generic form
  temp <- get(combinations[i])
  
  # Apply the fisher_transform function
  mean_edge_weights[i,] <- fisher_transform(temp)
}
```


```{r}
# Heatmap with full names
mean_edge_weights_melt <- melt(mean_edge_weights, 
                               varnames = c("Combination", "Edge"), 
                               value.name = "FisherZ")

# Restructuring names
names <- t(data.frame(strsplit(as.character(mean_edge_weights_melt$Combination), split = "_")))[,c(1:2,5)]
rownames(names) <- NULL
names[,c(1,3)] <- toupper(names[,c(1,3)])
names <- gsub('filt','Filtering',names)
names <- gsub('noFiltering','No Filtering',names)
mean_edge_weights_melt$names <- paste(names[,1],names[,2],names[,3],sep = ", ")

# heat map
ggplot(mean_edge_weights_melt, aes(x = Edge, y = names, fill = FisherZ)) +
    geom_tile() +
    scale_fill_gradient2(high = "red",
                         limit = c(min(mean_edge_weights),
                                   max(mean_edge_weights)),
                         name = "Fisher's Z") +
    labs(x = "Edge", y = "Preprocessing Combination", 
         title = "Heatmap of Mean Edgewise FC in the DMN by Preprocessing Combination") +
    geom_hline(yintercept = c(12.5,24.5,36.5), linewidth = 1.25) +
    geom_hline(yintercept = c(6.5,18.5,30.5,42.5), linewidth = 0.75, linetype = 2) 
```

```{r}
# Heatmap with only atlas names (fill in rest separately)
mean_edge_weights_melt <- melt(mean_edge_weights, 
                               varnames = c("Combination", "Edge"), 
                               value.name = "FisherZ")

# Restructuring names
names <- t(data.frame(strsplit(as.character(mean_edge_weights_melt$Combination), split = "_")))[,c(1:2,5)]
rownames(names) <- NULL
names[,c(1,3)] <- toupper(names[,c(1,3)])
#names <- gsub('filt','Filtering',names)
#names <- gsub('noFiltering','No Filtering',names)
atlas <- unique(names[,3])

# heat map
ggplot(mean_edge_weights_melt, aes(x = Edge, y = Combination, fill = FisherZ)) +
    geom_tile() +
    scale_fill_gradient2(high = "red",
                         limit = c(min(mean_edge_weights),
                                   max(mean_edge_weights)),
                         name = "Fisher's Z") +
    scale_x_discrete(expand=c(0,0)) +
    scale_y_discrete(expand = c(0,0), labels = rep(atlas,8)) +
    labs(x = "Edge", y = "") +
    theme(legend.text = element_text(size = 11,face = "bold"),
          legend.title = element_text(size = 12,face = "bold"),
          axis.title.x = element_text(size = 12,face = "bold"),
          axis.text.x = element_text(size = 11,face = "bold",colour = "black"),
          axis.text.y = element_text(size = 10,face = "bold",colour = "black")) +
    geom_hline(yintercept = c(12.5,24.5,36.5), linewidth = 1.25) +
    geom_hline(yintercept = c(6.5,18.5,30.5,42.5), linewidth = 0.75, linetype = 2) 
```

Ian original code

# big matrix and edge indices:
```{r}
# matrix with 6 edges (rows) and 48 combinations (columns)
big_matrix <- matrix(nrow = 6, ncol = 48)

# indices corresponding to the edges
edge_indices <- list(c(1, 2), c(1, 3), c(1, 4), c(2, 3), c(2, 4), c(3, 4))
```


# ###################### need to fix ######################
not all .RData are retrieved

# process each .RData file to populate big_matrix:
```{r}
for (i in seq_along(file_list)) {
    load(file_list[i])

    # get list contsins the matrices
    objs <- ls()
    list_name <- NULL
    for (obj_name in objs) {
        obj <- get(obj_name)
        if (is.list(obj) && all(sapply(obj, is.matrix))) {
            list_name <- obj_name
            break
        }
    }
    
    # get list of correlation matrices
    cor_matrices <- get(list_name)

    fisher_edges <- matrix(NA, nrow = length(edge_indices), ncol = length(cor_matrices))
    
    # fisher z
    for (j in seq_along(cor_matrices)) {
        for (k in seq_along(edge_indices)) {
            cor_value <- cor_matrices[[j]][edge_indices[[k]][1], edge_indices[[k]][2]]
            fisher_edges[k, j] <- ifelse(cor_value > -1 && cor_value < 1, atanh(cor_value), NA)  # NA if not valid
        }
    }
    
    # get the avg Fisher transformation for each edge, exclude NA values
    average_edges <- apply(fisher_edges, 1, function(x) mean(x, na.rm = TRUE))
    
    # check average_edges has length of 6
    if (length(average_edges) == 6) {
        big_matrix[, i] <- average_edges
    } else {
        warning(paste("Unexpected length of average_edges in", file_list[i]))
    }
}
```


# ######### may have better visual/plotting funtion potions, haven't created a heatmap before
# heat map
```{r}
# temp data
big_matrix_melted <- melt(big_matrix, varnames = c("Edge", "Combination"), value.name = "FisherZ")

# heat map
ggplot(big_matrix_melted, aes(x = Combination, y = Edge, fill = FisherZ)) +
    geom_tile() +
    scale_fill_gradient2(low = "blue",
                         high = "red",
                         mid = "green",
                         midpoint = 0,
                         limit = c(min(big_matrix, na.rm = TRUE),
                                   max(big_matrix, na.rm = TRUE)),
                         name = "Fisher Z") +
    labs(x = "Combination", y = "Edge")
```

