---
title: "Heatmap by Center"
author: "Xurui Zhi"
date: "2024-04-04"
output: html_document
---


# limit ggplot colors to have same range

# Prepare
```{r}
library(reshape2)
library(ggplot2)

# Define the base directory
base_dir <- "/Users/xuruizhi/Library/CloudStorage/OneDrive-ThePennsylvaniaStateUniversity/Scanner Heterogeneity Project/Correlation_Matrices/Matrices with center"
file_list <- list.files(path = base_dir, pattern = "\\.RData$", full.names = TRUE, ignore.case = TRUE)

# Define edges
edges <- c("MPFC:LP_L", "MPFC:LP_R", "LP_L:LP_R", "MPFC:PCC", "LP_L:PCC", "LP_R:PCC")

# The indices of the edges:
edge_indices <- list(
  "MPFC:LP_L" = c(1,2),
  "MPFC:LP_R" = c(1,3),
  "LP_L:LP_R" = c(2,3),
  "MPFC:PCC" = c(1,4),
  "LP_L:PCC" = c(2,4),
  "LP_R:PCC" = c(3,4)
)
```

# Data
```{r}
# List to store the combined data for each center
center_data <- list()

# Process each .RData file
for (file_path in file_list) {
  loaded_data <- load(file_path)
  data_variable_name <- loaded_data[1]
  data_variable <- get(data_variable_name)
  
  combination <- gsub("\\..*", "", basename(file_path))

  for (item in data_variable) {
    matrix <- item[["matrix"]]
    center <- item[["center"]]

    # If this is a new center, initialize a new matrix to hold the data
    if (!center %in% names(center_data)) {
      center_data[[center]] <- matrix(0, nrow = length(file_list), ncol = length(edges))
      rownames(center_data[[center]]) <- gsub("\\..*", "", basename(file_list))
      colnames(center_data[[center]]) <- names(edge_indices)
    }

    # Add Fisher Z-transformed values to the center's data
    for (edge_name in names(edge_indices)) {
      indices <- edge_indices[[edge_name]]
      # Extract the correlation value
      r <- matrix[indices[1], indices[2]]
      # Store the Fisher Z-transformed value
      center_data[[center]][combination, edge_name] <- mean(atanh(r))
    }
  }
}
```


# Graph
```{r}
# Create and save a heatmap for each center
for (center in names(center_data)) {
  # Melt the data for plotting
  melted_data <- melt(center_data[[center]], varnames = c("Combination", "Edge"), value.name = "FisherZ")

  # Generate the heatmap
  p <- ggplot(melted_data, aes(x = Edge, y = Combination, fill = FisherZ)) +
    geom_tile() +
    scale_fill_gradient2(high = "red", midpoint = 0, name="Fisher's Mean Z-transform", limit = c(-1, 2)) +
    labs(title = paste("Heatmap for Center:", center), x = "Edge", y = "Combination")

  # Save the heatmap
  ggsave(filename = paste0("new_heatmap_", gsub("[[:punct:]]", "", center), ".png"), plot = p, width = 10, height = 8)
}
```

